#!/bin/sh
/etc/init.d/bismark-authn-check enable
(crontab -l | grep -v bismark-authn-check; echo '0 0 * * 0 /usr/bin/bismark-authn-check') | crontab -
mv /etc/nodogsplash/htdocs/images/splash.html /etc/nodogsplash/htdocs/
