#ifndef _BISMARK_PASSIVE_CONSTANTS_H_
#define _BISMARK_PASSIVE_CONSTANTS_H_

#define DEBUG 1
#define PACKET_DATA_BUFFER_ENTRIES 65536
#define FLOW_TABLE_ENTRIES 65536
#define FLOW_TABLE_EXPIRATION_SECONDS (30*60)

#define NUM_MICROS_PER_SECOND 1e6

#endif
