#ifndef _BISMARK_PASSIVE_CONSTANTS_H_
#define _BISMARK_PASSIVE_CONSTANTS_H_

/*#define NDEBUG*/
#define PACKET_DATA_BUFFER_ENTRIES 65536
#define FLOW_TABLE_ENTRIES 65536
#define FLOW_TABLE_EXPIRATION_SECONDS (30*60)

#define DNS_TABLE_A_ENTRIES 1024
#define DNS_TABLE_CNAME_ENTRIES 1024

#define HT_NUM_PROBES 3
#define HT_C1 0.5
#define HT_C2 0.5

#define ENTRY_EMPTY     0
#define ENTRY_OCCUPIED  1
#define ENTRY_DELETED   2

#define NUM_MICROS_PER_SECOND 1e6

#endif
